### ISSUE TITLE
扫描登录报错

### ISSUE THREAD

**Issue by linshaolie** [xwartz/wechatApp-demo#1]
扫描登录， 然后出现错误：please bind your wechat account to the appid first

**Comment by xwartz** [comment]
好像现在登录有限制了，暂时没有什么方法，拉你入群？

**Comment by remxcode** [comment]
我也遇到了这个错误，可以拉我入群么？

**Comment by linshaolie** [comment]
在这里提供Q号？

**Comment by linshaolie** [comment]
@xwartz 在这里提供Q号？

**Comment by xwartz** [comment]
不用了，有方法了，先用老版本的登录，然后再用新版的登录

老版本去官网下载 https://mp.weixin.qq.com/wiki/10/e5f772f4521da17fa0d7304f68b97d7e.html

**Comment by xwartz** [comment]
我更新到 [wiki](https://github.com/xwartz/wechatApp-demo/wiki#%E5%8F%AF%E8%83%BD%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98) 了，如果解决了，请关闭一下。

**Comment by linshaolie** [comment]
@xwartz 好，我试试。AppID 需要填什么呢

**Comment by xwartz** [comment]
@linshaolie  随意填的

**Comment by agoodcoolman** [comment]
可以登录了，but现在appid不能使了。

**Comment by agoodcoolman** [comment]
@xwartz  appid直接报错什么原因

**Comment by xwartz** [comment]
@agoodcoolman  应该是你没有替换文件吧

**Comment by jackyon** [comment]
测试过了，确实可以登录了，谢谢 @xwartz 无私分享

**Comment by xwartz** [comment]
去下载官方版吧  不用破解了

**Comment by agoodcoolman** [comment]
<template is="odd" class="usermotto" data="{{...itemss}}"/>  能问一下，为啥模板里面的date的数据前面要加三个点？@xwartz

**Comment by xwartz** [comment]
@agoodcoolman   你是说对象前面加三个点吗？那是 es6 的对象扩展运算符，可以看下[阮一峰的教程](http://es6.ruanyifeng.com/#docs/object)

**Comment by agoodcoolman** [comment]
谢谢
