### ISSUE TITLE
scroll-view页面循环滚动很诡异

### ISSUE THREAD

**Issue by haha370104** [xwartz/wechatApp-demo#13]
表现就是到蓝色之后点一下依然是蓝色（最后一个）
但是点第二下会直接到红色（第二个）

看了一下循环那边实现有点诡异，order可以不需要为5个的
只用在tap的for循环里面对scrollView的长度取余就可以了

**Comment by Tyxiaomi** [comment]
问一下 微信小程序 怎么练weservice
