### ISSUE TITLE
刚上手 咨询一下,编译出现这个错误,把这行删掉才可以,是不是有问题

### ISSUE THREAD

**Issue by peter123023** [xwartz/wechatApp-demo#21]
VM1306:1 Mon Jan 08 2018 16:28:10 GMT+0800 (中国标准时间)  WXML 文件编译错误
VM1306:2 ./page/API/get-user-info/get-user-info.wxml
 unexpected tag, near `wx-imag...`
  14 |         </block>
  15 |         <block wx:if="{{hasUserInfo === true}}">
> 16 |           wx-image class="userinfo-avatar" src="{{userInfo.avatarUrl}}"></wx-image>
     |           ^
  17 |           <text class="userinfo-nickname">{{userInfo.nickName}}</text>
  18 |         </block>
  19 |       </view>

**Comment by huangyongsong** [comment]
<wx-image class="userinfo-avatar" src="{{userInfo.avatarUrl}}"></wx-image>这行报错

**Comment by huangyongsong** [comment]
```   <wx-image class="userinfo-avatar" src="{{userInfo.avatarUrl}}"></wx-image>` 这行报错

**Comment by cydjohn** [comment]
wx-image 改成 image 就可以了
