### ISSUE TITLE
windows不能创建项目

### ISSUE THREAD

**Issue by agoodcoolman** [xwartz/wechatApp-demo#4]
![qq 20160923121044](https://cloud.githubusercontent.com/assets/11003275/18773999/2beb5444-8187-11e6-8720-8061a09e1be4.png)

window 已经用破解文件 破击了。

**Comment by LCINA** [comment]
有什么破解文件  我也是这个错误 @xwartz @agoodcoolman 怎么破

**Comment by agoodcoolman** [comment]
请看 主页README.md 下面的破解

**Comment by LCINA** [comment]
那个好像只适用于mac

**Comment by xwartz** [comment]
@LCINA  只是目录路径不一样，资源是一样的

**Comment by LCINA** [comment]
可以了  分享个链接：http://mp.weixin.qq.com/s?__biz=MzI1NDE5NjMyMA==&mid=2652022785&idx=1&sn=ee9287da9790725430b1417c6265b9e7&chksm=f22ee70ec5596e1845866e49776b3fc3c28505a72c43ffb76f40eac44c5b37b6e5c5b9610625&scene=1&srcid=0923v6Eqr3SqDFHrtd7d88aU#rd

**Comment by agoodcoolman** [comment]
@xwartz demo地址下载失效了。

**Comment by xwartz** [comment]
@agoodcoolman  demo 可以直接那这个仓库的

**Comment by agoodcoolman** [comment]
我的微信公众号 appid 没有绑定什么的，反正不能用

**Comment by xwartz** [comment]
去下载官方版吧  不用破解了
