### ISSUE TITLE
JS TypeError

### ISSUE THREAD

**Issue by stopro** [xwartz/wechatApp-demo#5]
TypeError: Cannot read property 'MaxRequestConcurrent' of undefined
    at http://1214303409.appservice.open.weixin.qq.com/asdebug.js:1:5840
    at http://1214303409.appservice.open.weixin.qq.com/asdebug.js:1:9997(anonymous function) @ asdebug.js:1(anonymous function) @ asdebug.js:1
WAService.js:2 App: onLaunch have been invoked

**Comment by xwartz** [comment]
把 [asdebug.js](https://github.com/gavinkwoe/weapp-ide-crack/archive/master.zip) 文件替换一下

**Comment by xwartz** [comment]
目录 

Mac： /Resources/app.nw/app/dist/weapp/appservice/asdebug.js

WIndows：\package.nw\app\dist\weapp\appservice\asdebug.js

**Comment by xwartz** [comment]
去下载官方版吧  不用破解了
